service: bootcamp-clonenetflix-nodejs
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 30
  environment:
    MONGO_URI: 'mongodb+srv://sa_rbiasibetti:WiaSU7QTnhtskDd@rbiasibetti.phxqc.mongodb.net/rbiasibetti?retryWrites=true&w=majority'
    TOKEN_SECRET: 'secretPass'
plugins:
  - serverless-plugin-typescript
  - serverless-offline
functions:
  app:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true